### ISSUE TITLE
支付宝花呗还款失败后就停止解析

### ISSUE THREAD

**Issue by Jousimies** [zsxsoft/my-beancount-scripts#12]
如题，怎么自动忽略这条记录？

**Comment by zsxsoft** [comment]
https://github.com/zsxsoft/my-beancount-scripts/blob/master/modules/imports/alipay_prove.py#L134
这里有几个exit(0)，去掉即可

本意是让自己发现还有哪些无法解析的账单详情并修复，如果可以的话楼主可以把print出来的那一行贴出来看看？

**Comment by Jousimies** [comment]
搞定了，我加了句elif status =='还款失败'。
