### ISSUE TITLE
导入带有支付渠道的支付宝账单压缩文件 提示文件编码不能正确解码

### ISSUE THREAD

**Issue by RenLangMan** [zsxsoft/my-beancount-scripts#13]
支付宝App->我的->账单->右上角...->开具交易流水证明，之后可在邮箱中得到zip文件。

通过import.py导入时，脚本会提示输入密码。

我用下面的命令
 `python import.py alipay_record_20210708_114333.zip --entry main.bean --out File01.bean`
将压缩包内容解压导入File01.bean文件中，
因为压缩包加密了，提示要输入解压密码，我输入了密码后提示非法的字节序列，无法自动解码文件
`
File 'alipay_record_20210708_114333.csv' is encrypted, password required for extraction

支付宝账单密码：234512

'gbk' codec can't decode byte 0x99 in position 64: illegal multibyte sequence

'utf-8' codec can't decode byte 0xe8 in position 12: invalid continuation byte

No suitable importer!
`
有碰到类似的问题的吗，应该怎么解决

**Comment by zsxsoft** [comment]
手动解压试一下，可能写错了

**Comment by RenLangMan** [comment]
手动用7zip可以输入密码234512得到单个csv文件，但是脚本中传入的参数是带密码的压缩包文件，如何将脚本改为读取解压后csv文件？

**Comment by zsxsoft** [comment]
会自动识别zip和csv的

**Comment by RenLangMan** [comment]
调用zipfile对传统加密的zip文件进行解压可以成功，但是当zip为非传统加密方式时无法解压，这里的传统加密指的什么呢？大家使用版本比较新的WinRAR进行zip加密压缩的时候，下面会有一个“ZIP传统加密'的选项:

![传统加密](https://img-blog.csdnimg.cn/img_convert/97c6659871cbb447e71de65814d4228c.png)

当博主不勾选这个选项生成压缩包进行解压测试的时候，发现无法解压：

![报错图](https://img-blog.csdnimg.cn/img_convert/f3001cca516839b880b4f626fdd2f677.png)

后查询资料得出如下解释：
默认情况下，WinRAR在CTR模式下使用AES-256加密ZIP文件，而传统加密是通过CRC32加密，也即ZIP 2.0传统加密算法，
虽然AES-256比ZIP 2.0传统加密算法安全得多，但它可能与一些旧的解压软件不兼容，
而Python标准库中的zipfile模块只支持CRC32加密的zip文件，
所以不采用传统加密方式是无法通过zipfile库进行解压的。

支付宝账单zip文件加密模算法: AES-256 Deflate是无法通过zipfile库解压的

**Comment by RenLangMan** [comment]
下面三种方法可以在python中正确运行7z命令：

# 方法1： 拷贝 7z.exe 和7z.dll 到当前python文件所在的目录下。 否则，不认识7z 命令。
zip_command = '7z a -tzip {0} {1} -r'.format(target, ' '.join(source))

# 方法2： os.system() 里面执行的是同目录下的exe, 使用如下os.chdir() 命令切换 path。
os.chdir('D:\\Program Files (x86)\\7-Zip')
print('切换当前路径为：', os.getcwd())
zip_command = '7z a -tzip {0} {1} -r'.format(target, ' '.join(source))

# 方法3：在cmd 命令中写入7z.exe所在的目录
zip_command = '"D:\\Program Files (x86)\\7-Zip\\7z.exe" a -tzip {0} {1} '.format(target, ' '.join(source))


————————————————
版权声明：本文为CSDN博主「紫色蜘蛛爬啊爬」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
原文链接：https://blog.csdn.net/zzphapy/article/details/81502837

**Comment by RenLangMan** [comment]
我修改了压缩代码 调用外部软件7zip给文件解压，读取到bytes数据后删除得到的csv文件

**Comment by quando** [comment]
我也碰到相关问题了，不知道是不是跟你们一样，反正这几个月我是解压缩处csv文件再import的
`D:\workspace-idea\my-beancount-scripts>python import.py ./alipay_record_20210727_213927.zip
File 'alipay_record_20210727_213927.csv' is encrypted, password required for extraction
支付宝账单密码：
'gbk' codec can't decode byte 0x99 in position 64: illegal multibyte sequence
'utf-8' codec can't decode byte 0xed in position 10: invalid continuation byte
exceptions must derive from BaseException
exceptions must derive from BaseException
exceptions must derive from BaseException
exceptions must derive from BaseException
exceptions must derive from BaseException
exceptions must derive from BaseException
No suitable importer!
`

**Comment by zsxsoft** [comment]
@quando 尝试解压一下再试试 @RenLangMan 提交的patch路径写死不太合适，我近期有空再看一下这块
