### ISSUE TITLE
请教一下账单去重问题

### ISSUE THREAD

**Issue by sandianyiyuan** [zsxsoft/my-beancount-scripts#18]
自述文件中说：`如果同一天存在两笔同金额交易，则需要人工处理`  
后面又说：`如果同时导入支付宝、微信和银行账单，必然会重复。如在导入支付宝、微信账单时，发现正在导入的交易已经存在，则会为原先已存在的交易添加支付宝和微信的订单号及时间戳，不会重复导入同一笔交易。`
这个`不会重复导入` 操作是脚本自动识别的还是说需要人工干预？

**Comment by zsxsoft** [comment]
自动识别
