### ISSUE TITLE
accounts.py文件配置了后，消费分类部分能识别，部分无法识别....不知道是不是输入格式的问题。

### ISSUE THREAD

**Issue by kklod** [zsxsoft/my-beancount-scripts#19]

**Comment by kklod** [comment]
刚刚看了下，原来消费分类是通过商品内容与配置文件中的字典匹配实现的，我之前误以为是通过商家信息与字典的匹配实现的。个人觉得其实与商家信息进行匹配会比较好一点，因为一些个人商贩，包括小的店铺，棋商品信息多为“收款方备注:二维码收款”此类无用信息，不利于识别分类。

**Comment by zsxsoft** [comment]
https://github.com/zsxsoft/my-beancount-scripts/blob/master/modules/imports/__init__.py#L12
当商品详情为空时才会按商家匹配，可以稍微调下规则
