### ISSUE TITLE
运行脚本提示“充值成功”就停止了

### ISSUE THREAD

**Issue by ljh19930603** [zsxsoft/my-beancount-scripts#20]
![image](https://user-images.githubusercontent.com/25343841/147876239-2a1521a1-5c2c-4169-bc1d-7ff76b42bf0d.png)
![image](https://user-images.githubusercontent.com/25343841/147876277-518d6eab-def4-4207-bd60-f79c981c5aca.png)

**Comment by kklod** [comment]
感觉像是随机停止的   我也遇到这这种情况  也不报错……
<img width="541" alt="image" src="https://user-images.githubusercontent.com/50442661/179358547-aedc1f61-a9ae-4ebe-85fb-4ffe3b9ba924.png">

**Comment by zsxsoft** [comment]
不是随机停止的，像你们这种状态我的账单里都没有，我也不知道怎么处理，只能停止。
这个你应该自己改一下代码，代码里有类似的部分复制粘贴一下
