### ISSUE TITLE
支付宝“alipay_prove"第38行减去30，会造成部分账单被漏掉了，我这里账单后面只有20行导出消息。

### ISSUE THREAD

**Issue by Mai19930513** [zsxsoft/my-beancount-scripts#23]
https://github.com/zsxsoft/my-beancount-scripts/blob/6f559ae15541887de9c9b995fc82c0fa3420967a/modules/imports/alipay_prove.py#L38
![微信截图_20220315154614](https://user-images.githubusercontent.com/7880084/158330294-36605e43-68dc-4be6-b7d7-107e6fa7152c.png)

**Comment by zsxsoft** [comment]
这个很奇怪，我之前是30，可能是会更新？
得加一个自动识别，回头弄弄。
