### ISSUE TITLE
wechat.py 退款有bug

### ISSUE THREAD

**Issue by RukawaKaede** [zsxsoft/my-beancount-scripts#4]
你好！感谢你的代码:-)，发现一点小问题：
wechat.py中[退款这里](https://github.com/zsxsoft/my-beancount-scripts/blob/beaa507b0725e377fc2022030ffbd34229df3a57/modules/imports/wechat.py#L70)有问题，我实际测了一下，发现它会全部计算到Expense中。

**Comment by zsxsoft** [comment]
我也发现了，先这样放着，回头慢慢处理
